name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_esp32:

    name: build esp32

    runs-on: ubuntu-latest

    strategy:
      matrix:
        fqbn:
          - esp32:esp32:esp32

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          
      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.fqbn }}
          platforms: |
            - name: esp32:esp32
              source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
              version: 2.0.13
          sketch-paths: |
            - examples/ml_epiano_example
            - examples/ml_mod_tracker
            - examples/ml_synth_basic_example
            - examples/ml_synth_fm_example
            - examples/ml_synth_multi_saw_example
            - examples/ml_synth_organ_example
            - examples/ml_synth_pwm_osc_example
            - examples/ml_synth_sampler_example
          libraries: |
              - source-url: https://github.com/marcel-licence/ML_SynthTools.git
                name: ML_SynthTools
              - source-url: https://github.com/marcel-licence/ML_SynthTools_Lib.git
                name: ML_SynthTools_Lib
              - source-url: https://github.com/adafruit/Adafruit-GFX-Library.git
                name: Adafruit_GFX_Library
                version: 1.10.10
              - source-url: https://github.com/adafruit/Adafruit_SSD1306.git
                name: Adafruit_SSD1306
                version: 2.4.5
              - source-url: https://github.com/adafruit/Adafruit_BusIO.git
                name: Adafruit BusIO
                version: 1.14.1
              - source-url: https://github.com/marcel-licence/AC101.git
                name: AC101

  build_esp8266:

    name: build esp8266

    runs-on: ubuntu-latest

    strategy:
      matrix:
        fqbn:
          - esp8266:esp8266:d1_mini

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          
      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.fqbn }}
          platforms: |
            - name: esp8266:esp8266
              source-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
              version: 3.1.2
          sketch-paths: |
            # - examples/ml_epiano_example
            - examples/ml_mod_tracker
            # - examples/ml_synth_basic_example
            # - examples/ml_synth_fm_example
            # - examples/ml_synth_multi_saw_example
            - examples/ml_synth_organ_example
            # - examples/ml_synth_pwm_osc_example
            # - examples/ml_synth_sampler_example
          libraries: |
              - source-url: https://github.com/marcel-licence/ML_SynthTools.git
                name: ML_SynthTools
              - source-url: https://github.com/marcel-licence/ML_SynthTools_Lib.git
                name: ML_SynthTools_Lib
              - source-url: https://github.com/adafruit/Adafruit-GFX-Library.git
                name: Adafruit_GFX_Library
                version: 1.10.10
              - source-url: https://github.com/adafruit/Adafruit_SSD1306.git
                name: Adafruit_SSD1306
                version: 2.4.5
              - source-url: https://github.com/adafruit/Adafruit_BusIO.git
                name: Adafruit BusIO
                version: 1.14.1
              - source-url: https://github.com/marcel-licence/AC101.git
                name: AC101

  build_rp2040:

    if: false

    name: build rp2040

    runs-on: ubuntu-latest

    strategy:
      matrix:
        fqbn:
          - rp2040:rp2040:rpipico

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.fqbn }}
          platforms: |
            - name: rp2040:rp2040
              source-url: https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json
          sketch-paths: |
            - ./
          libraries: |
              - source-url: https://github.com/marcel-licence/ML_SynthTools.git
                name: ML_SynthTools
              - source-url: https://github.com/FortySevenEffects/arduino_midi_library.git
                name: MIDI_Library
                version: 5.0.2

  build_stm32:

    if: false

    name: build stm32

    runs-on: ubuntu-latest

    strategy:
      matrix:
        fqbn:
          - STMicroelectronics:stm32:GenH7

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          
      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.fqbn }}
          platforms: |
            - name: STMicroelectronics:stm32
            - source-url: https://raw.githubusercontent.com/stm32duino/BoardManagerFiles/main/package_stmicroelectronics_index.json
              version: 2.0.0
          sketch-paths: |
            - examples/ml_epiano_example
            - examples/ml_mod_tracker
            - examples/ml_synth_basic_example
            - examples/ml_synth_fm_example
            - examples/ml_synth_multi_saw_example
            - examples/ml_synth_organ_example
            - examples/ml_synth_pwm_osc_example
            - examples/ml_synth_sampler_example
          libraries: |
              - source-url: https://github.com/marcel-licence/ML_SynthTools.git
                name: ML_SynthTools
              - source-url: https://github.com/marcel-licence/ML_SynthTools_Lib.git
                name: ML_SynthTools_Lib
              - source-url: https://github.com/adafruit/Adafruit-GFX-Library.git
                name: Adafruit_GFX_Library
                version: 1.10.10
              - source-url: https://github.com/adafruit/Adafruit_SSD1306.git
                name: Adafruit_SSD1306
                version: 2.4.5
              - source-url: https://github.com/adafruit/Adafruit_BusIO.git
                name: Adafruit BusIO
                version: 1.14.1
              - source-url: https://github.com/marcel-licence/AC101.git
                name: AC101

  build_teensy:

    if: true

    name: build teensy

    runs-on: ubuntu-latest

    strategy:
      matrix:
        fqbn:
          - teensy:avr:teensy41

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          
      - name: Compile sketch
        uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.fqbn }}
          platforms: |
            - name: teensy:avr
              source-url: https://www.pjrc.com/teensy/package_teensy_index.json
              version: 1.59.0
          sketch-paths: |
            #- examples/ml_epiano_example
            #- examples/ml_mod_tracker
            - examples/ml_synth_basic_example
            - examples/ml_synth_fm_example
            #- examples/ml_synth_multi_saw_example
            #- examples/ml_synth_organ_example
            #- examples/ml_synth_pwm_osc_example
            #- examples/ml_synth_sampler_example
          libraries: |
              - source-url: https://github.com/marcel-licence/ML_SynthTools.git
                name: ML_SynthTools
              - source-url: https://github.com/marcel-licence/ML_SynthTools_Lib.git
                name: ML_SynthTools_Lib
              - source-url: https://github.com/adafruit/Adafruit-GFX-Library.git
                name: Adafruit_GFX_Library
                version: 1.10.10
              - source-url: https://github.com/adafruit/Adafruit_SSD1306.git
                name: Adafruit_SSD1306
                version: 2.4.5
              - source-url: https://github.com/adafruit/Adafruit_BusIO.git
                name: Adafruit BusIO
                version: 1.14.1
              - source-url: https://github.com/marcel-licence/AC101.git
                name: AC101
